### ISSUE TITLE
Sometimes condition go to if or else for 0 reason

### ISSUE THREAD

**Issue by AntoineNavarro2** [bahmutov/cypress-if#54]
![Capture d’écran 2022-11-22 153325](https://user-images.githubusercontent.com/43134654/203341310-8402e293-9653-4b4a-8123-0f733eaffb16.png)
![Capture d’écran 2022-11-22 153601](https://user-images.githubusercontent.com/43134654/203341315-99075cbf-41a1-4bbc-892b-17fdcd215e05.png)

**Comment by bahmutov** [comment]
What is the Cypress version you are using?

**Comment by AntoineNavarro2** [comment]
> What is the Cypress version you are using?

V11.1.0

**Comment by bahmutov** [comment]
Can you try the latest release of this plugin https://github.com/bahmutov/cypress-if/releases/tag/v1.10.2 because it fixes Cypress v11.1.0 compatibility (see #53)

**Comment by AntoineNavarro2** [comment]
> Can you try the latest release of this plugin https://github.com/bahmutov/cypress-if/releases/tag/v1.10.2 because it fixes Cypress v11.1.0 compatibility (see #53)

It's work again thanks ! Where does the problem come from ?

**Comment by bahmutov** [comment]
The cypress version changed how it flags a skipped command Sent from my iPhoneOn Nov 22, 2022, at 10:11, AntoineNavarro2 ***@***.***> wrote:﻿

Can you try the latest release of this plugin https://github.com/bahmutov/cypress-if/releases/tag/v1.10.2 because it fixes Cypress v11.1.0 compatibility (see #53)

It's work again thanks ! Where does the problem come from ?
